name: Cache Node Modules (pnpm)

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - uses: actions/cache@v3
              id: node_modules_cache
              with:
                  path: './node_modules'
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('./pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - run: pnpm install --frozen-lockfile
